# Generated by Django 5.2.4 on 2025-08-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите марку автомобиля",
                        max_length=100,
                        verbose_name="Марка автомобиля",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание автомобиля",
                        null=True,
                        verbose_name="Описание автомобиля",
                    ),
                ),
                (
                    "image_url",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение автомобиля",
                        null=True,
                        upload_to="product/image",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Введите дату создания",
                        null=True,
                        verbose_name="Дата создания",
                    ),
                ),
                ("publication_flag", models.IntegerField(blank=True, null=True)),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество просмотров",
                        verbose_name="Счетчик просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
                "ordering": ["creation_date", "title"],
            },
        ),
    ]
